name: Setup
description: Boilerplate steps needed by most jobs.
inputs:
  bun-version:
    description: Version of Bun to use.
    required: false
    default: 1.3.6
  install-deps:
    description: Should deps be installed?
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Use Bun ${{inputs.bun-version}}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{inputs.bun-version}}
    - name: Install Dependencies
      run: bun install --frozen-lockfile
      shell: bash
      if: ${{inputs.install-deps}} == 'true'
