/**
 * @module cli/commands/apply
 *
 * Execute a release plan previously generated by `release plan`.
 *
 * Reads the plan from `.release/plan.json`, runs preflight checks,
 * publishes packages, creates git tags, pushes tags, and creates
 * GitHub releases. Supports `--dry-run` for inspection and `--yes`
 * to skip the interactive confirmation prompt (for CI).
 */
import { Terminal } from '@effect/platform'
import { Cli } from '@kitz/cli'
import { Env } from '@kitz/env'
import { Fs } from '@kitz/fs'
import { Git } from '@kitz/git'
import { NpmRegistry } from '@kitz/npm-registry'
import { Oak } from '@kitz/oak'
import { Console, Effect, Fiber, Layer, Option, Schema, Stream } from 'effect'
import * as Api from '../../api/__.js'
import { CommandExecutorLayer, FileSystemLayer, TerminalLayer } from '../../platform.js'

/**
 * release apply
 *
 * Execute the release plan. Requires plan file from 'release plan'.
 */
const args = Oak.Command.create()
  .use(Oak.EffectSchema)
  .description('Execute the release plan')
  .parameter(
    'yes y',
    Schema.transform(Schema.UndefinedOr(Schema.Boolean), Schema.Boolean, {
      strict: true,
      decode: (v) => v ?? false,
      encode: (v) => v,
    }).pipe(
      Schema.annotations({ description: 'Skip confirmation prompt (for CI)', default: false }),
    ),
  )
  .parameter(
    'dry-run d',
    Schema.transform(Schema.UndefinedOr(Schema.Boolean), Schema.Boolean, {
      strict: true,
      decode: (v) => v ?? false,
      encode: (v) => v,
    }).pipe(
      Schema.annotations({ description: 'Preview actions without executing', default: false }),
    ),
  )
  .parameter(
    'tag t',
    Schema.UndefinedOr(Schema.String).pipe(
      Schema.annotations({ description: 'npm dist-tag (default: latest)' }),
    ),
  )
  .parse()

const confirm = (message: string) =>
  Effect.gen(function* () {
    const terminal = yield* Terminal.Terminal
    yield* terminal.display(message)
    const answer = yield* terminal.readLine.pipe(Effect.catchAll(() => Effect.succeed('')))
    const normalized = answer.trim().toLowerCase()
    return normalized === 'y' || normalized === 'yes'
  })

const commandLayer = CommandExecutorLayer
const npmLayer = NpmRegistry.NpmCliLive.pipe(Layer.provide(commandLayer))

Cli.run(
  Layer.mergeAll(
    Env.Live,
    FileSystemLayer,
    TerminalLayer,
    Git.GitLive,
    commandLayer,
    npmLayer,
  ),
)(
  Effect.gen(function* () {
    const env = yield* Env.Env

    // Load plan file using schema-validated resource
    const planDir = Fs.Path.join(env.cwd, Api.Planner.PLAN_DIR)
    const planFileOption = yield* Api.Planner.resource.read(planDir)

    if (Option.isNone(planFileOption)) {
      yield* Console.error(`No release plan found at ${Fs.Path.toString(Api.Planner.PLAN_FILE)}`)
      yield* Console.error(
        `Run 'release plan --lifecycle <official|candidate|ephemeral>' first to generate a plan.`,
      )
      return env.exit(1)
    }

    // Load config (scanning packages is no longer needed - plan has full PlannedRelease data)
    const config = yield* Api.Config.load()

    // Plan file now stores rich PlannedRelease data directly - no conversion needed
    const plan = planFileOption.value
    const tag = args.tag ?? (plan.lifecycle === 'official' ? config.npmTag : config.candidateTag)

    // Confirmation prompt (unless --yes)
    if (!args.yes && !args.dryRun) {
      yield* Console.log(Api.Renderer.renderApplyConfirmation(plan))
      const approved = yield* confirm('Proceed with release? [y/N] ')
      if (!approved) {
        yield* Console.log('Release canceled.')
        return env.exit(1)
      }
    }

    if (args.dryRun) {
      yield* Console.log(Api.Renderer.renderApplyDryRun(plan))
      return
    }

    const runtime = yield* Api.Explorer.explore()
    const runtimeConfig = Api.Explorer.toExecutorRuntimeConfig(runtime)
    if (!runtimeConfig.github) {
      yield* Console.error('GitHub release target and token are required for release apply.')
      yield* Console.error('Set GITHUB_TOKEN and ensure origin points to GitHub, then retry.')
      return env.exit(1)
    }

    // Execute with observable workflow
    const { events, execute } = yield* Api.Executor.executeObservable(plan, {
      dryRun: args.dryRun,
      tag,
      publishing: config.publishing,
      trunk: config.trunk,
      github: runtimeConfig.github,
    })

    // Fork event consumer to stream status updates
    const eventFiber = yield* events.pipe(
      Stream.tap((event) => {
        const line = Api.Executor.formatLifecycleEvent(event)
        if (!line) return Effect.void
        return line.level === 'error' ? Console.error(line.message) : Console.log(line.message)
      }),
      Stream.runDrain,
      Effect.fork,
    )

    // Run workflow
    const result = yield* execute

    // Wait for events to flush
    yield* Fiber.join(eventFiber)

    yield* Console.log(Api.Renderer.renderApplyDone(result.releasedPackages.length))

    // Clean up plan file on success
    const planPath = Fs.Path.join(env.cwd, Api.Planner.PLAN_FILE)
    yield* Fs.remove(planPath)
  }),
)
