/**
 * @module cli/commands/apply
 *
 * Execute a release plan previously generated by `release plan`.
 *
 * Reads the plan from `.release/plan.json` by default, runs preflight checks
 * (see `apply-lib.ts` for the gate gauntlet), publishes packages, creates git
 * tags, pushes tags, and creates GitHub releases. Use `--yes` to skip the
 * interactive confirmation prompt (for CI). For non-mutating review use
 * `release preview` before applying.
 */
import { Env } from '@kitz/env'
import { Fs } from '@kitz/fs'
import { Git } from '@kitz/git'
import { Github } from '@kitz/github'
import { Console, Effect, Layer } from 'effect'
import { Command, Flag } from 'effect/unstable/cli'
import * as Artifact from '../../api/artifact.js'
import * as Clock from '../../api/clock.js'
import * as Config from '../../api/config.js'
import * as Executor from '../../api/executor/__.js'
import * as Explorer from '../../api/explorer/__.js'
import * as Lock from '../../api/lock.js'
import * as Planner from '../../api/planner/__.js'
import * as Proof from '../../api/proof.js'
import * as Publishing from '../../api/publishing.js'
import * as Renderer from '../../api/renderer/__.js'
import { ChildProcessSpawnerLayer, TerminalLayer } from '../../platform.js'
import { CommandBaseLayer, NpmCliLayer, failWith, fromFlag, rejectFrozenTag } from './_shared.js'
import { applyPreflightGates, runPreflightGates } from './apply-lib.js'
import { confirm, runObservableCommand } from './execution.js'
import { loadExecutableCommandPlan } from './plan-file.js'

export const apply = Command.make(
  'apply',
  {
    yes: Flag.boolean('yes').pipe(
      Flag.withAlias('y'),
      Flag.withDescription('Skip confirmation prompt (for CI)'),
      Flag.withDefault(false),
    ),
    prove: Flag.boolean('prove').pipe(
      Flag.withDescription('Refresh plan-bound proof before apply'),
      Flag.withDefault(false),
    ),
    rehearse: Flag.boolean('rehearse').pipe(
      Flag.withDescription('Refresh artifact manifest before apply'),
      Flag.withDefault(false),
    ),
    tag: Flag.string('tag').pipe(
      Flag.withAlias('t'),
      Flag.withDescription('npm dist-tag override'),
      Flag.optional,
    ),
    from: fromFlag,
    allowPrereleaseLatest: Flag.boolean('allow-prerelease-latest').pipe(
      Flag.withDescription('Permit a prerelease plan to publish to the `latest` dist-tag'),
      Flag.withDefault(false),
    ),
  },
  ({ yes, prove, rehearse, tag, from, allowPrereleaseLatest }) =>
    Effect.gen(function* () {
      const env = yield* Env.Env

      yield* rejectFrozenTag(tag)

      const executablePlan = yield* loadExecutableCommandPlan(from)
      const plan = executablePlan.plan

      // Single intent resolver: resolves the frozen publish intent and enforces
      // the prerelease-to-`latest` guard before any mutation.
      const intentResult = yield* Effect.result(
        Publishing.resolvePublishIntentForPlan(plan, { allowPrereleaseLatest }),
      )
      if (intentResult._tag === 'Failure') {
        return yield* failWith(intentResult.failure.message)
      }
      const publish = Publishing.publishSemanticsFromIntent(intentResult.success)
      const planDigest = executablePlan.planDigest
      const lockNow = yield* Clock.now

      const lockParams = {
        planDigest,
        ownerId: env.vars['USER'] ?? 'local-operator',
        ownerHost: env.vars['HOST'] ?? env.vars['HOSTNAME'] ?? 'local-host',
        ownerProcess: env.vars['KITZ_RELEASE_PROCESS_ID'] ?? 'local-process',
        now: lockNow,
      } satisfies Lock.LocalLockParams

      // Confirmation prompt (unless --yes)
      if (!yes) {
        const releaseCommand = yield* Config.load().pipe(
          Effect.map((config) => config.operator.releaseCommand),
          Effect.catch(() => Effect.succeed('release')),
        )
        yield* Console.log(
          Renderer.renderApplyConfirmation(plan, publish, {
            env: env.vars,
            releaseCommand,
          }),
        )
        const approved = yield* confirm('Proceed with release? [y/N] ')
        if (!approved) {
          yield* Console.log('Release canceled.')
          return env.exit(1)
        }
      }

      const applied = yield* Lock.withLocal(
        lockParams,
        Effect.gen(function* () {
          if (prove) {
            const localObservations = yield* Proof.collectLocalObservations(plan)
            const githubObservations = yield* Explorer.resolveGitHubContext().pipe(
              Effect.flatMap((context) =>
                Proof.collectGithubObservations(plan).pipe(
                  Effect.provide(
                    Github.LiveFetch({
                      owner: context.target.owner,
                      repo: context.target.repo,
                      ...(context.token !== null ? { token: context.token } : {}),
                    }),
                  ),
                ),
              ),
              Effect.catch(() => Effect.succeed({})),
            )
            const proof = yield* Proof.prove(plan, {
              ...localObservations,
              ...githubObservations,
            })
            if (Proof.hasBlockingProof(proof, yield* Clock.now)) {
              yield* Console.error(
                'Plan proof contains blocking records. Run `release prove` for detail.',
              )
              return false
            }
          }

          if (rehearse) {
            yield* Artifact.rehearse(plan)
          }

          const preflightFailure = yield* runPreflightGates(applyPreflightGates(plan))
          if (preflightFailure !== null) {
            yield* Console.error(preflightFailure.lines.join('\n'))
            return false
          }

          const runtime = yield* Explorer.explore()
          const runtimeConfig = Explorer.toExecutorRuntimeConfig(runtime)
          if (!runtimeConfig.github) {
            yield* Console.error(
              [
                'GitHub release target and token are required for release apply.',
                'Set GITHUB_TOKEN and ensure origin points to GitHub, then retry.',
              ].join('\n'),
            )
            return false
          }

          yield* runObservableCommand(
            yield* Executor.executeObservable(plan, {
              dryRun: false,
              tag: publish.distTag,
              rehearsedArtifacts: true,
              ...(plan.publishIntent !== undefined
                ? { registry: plan.publishIntent.registry.url }
                : {}),
              ...(plan.publishIntent !== undefined ? { trunk: plan.publishIntent.git.trunk } : {}),
              github: runtimeConfig.github,
            }),
          )

          // Archive the executed plan immutably by digest, then clear the
          // active pointer (instead of deleting the only copy of the plan).
          const archiveFile = yield* Planner.Store.archive(plan, planDigest)
          yield* Console.log(`Plan archived to ${Fs.Path.toString(archiveFile)}`)
          if (executablePlan.source === 'active') {
            yield* Planner.Store.deleteActive
          }

          return true
        }),
      )

      if (!applied) {
        return env.exit(1)
      }
    }),
).pipe(
  Command.withDescription('Execute the release plan'),
  Command.provide(
    Layer.mergeAll(
      CommandBaseLayer,
      TerminalLayer,
      Git.GitLive,
      ChildProcessSpawnerLayer,
      NpmCliLayer,
    ),
  ),
)
